title: My Personal Blog
email: your-email@example.com
description: >-
  Welcome to my personal blog where I share my thoughts and experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
minima:
  date_format: "%b %-d, %Y"
  skin: classic
  show_excerpts: false

# Set the excerpt separator
excerpt_separator: <!--more-->

# Collections
collections:
  my_posts:
    output: true
    permalink: /my_posts/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "my_posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 